Day 6
MikeSki61/GROCERY_LIST_APP pull request #19
Opened 2024-12-02 10:39 UTC by MikeSki61

Updated code to PEP-8 code standards.
Cleaned up code.
Corrected indents and white spaces.
Variables are to standard.

2024-12-02 18:07 UTC, SkylerFines requested changes
Hi Mike,

I've submitted the first round of suggestions for review. Additionally, I recommend updating the pull request to align with the provided template. There are some formatting issues and missing details, such as the summary and the changes made.

I also suggest renaming the repository from "exercises" to something more descriptive or specific to your app for better clarity and organization.

2024-12-03 03:11 UTC, MikeSki61 commented on mkl_core.py
> +grocery_list: list[dict[str, float | int | bool | str]] = [
Left a comment above the grocery_list telling a new user what it is, keywords and values.
# The grocery_list is a list of items showing the keywords and values of each.
# Also this shows the type of item within the list ex: "name" is a string, 
# cost is a float, priority is an integer and buy is a boolean.-True or False.

2024-12-03 03:20 UTC, MikeSki61 commented on mkl_core.py
> +    if buy_list:
refactored the code using the f string. I wasn't too clear on how to take that approach.

2024-12-03 03:31 UTC, MikeSki61 commented on mkl_core.py
> +grocery_list: list[dict[str, float | int | bool | str]] = [
"""
mk_core.py
This file is the core file that provides the functions for the app.
It includes the ability to add, remove, edit, and export the list.

Functions are:
- add_items(): Add items to the list.
-remove_items(): Removes items from the list.
-edit_items(): Edits any item within the list. Any value can be edited.
-export_items(): Able to export the list.

Author: Mike Kwiatkowsky
Version:1.0.0
"""

2024-12-03 11:34 UTC, MikeSki61 commented on mkl_core.py
> +def add_item(name: str, store: str, cost: float,
Added  a dco string for each function describing what the function does.

2024-12-03 11:41 UTC, MikeSki61 commented on mkl_launch.py
>  print("Welcome to your Grocery Shopping List!")
Moved the print statement to inside the launch function

2024-12-03 11:43 UTC, MikeSki61 commented on mkl_launch.py
Added doc string at the top of the file
"""
mk_launch.py
This file is the launch file that imports the functions for the app.
It includes the ability to add, remove, edit, and export the list.

Functions are:
-add_items(): Add items to the list.
-remove_items(): Removes items from the list.
-edit_items(): Edits any item within the list. Any value can be edited.
-export_items(): Able to export the list.

Author: Mike Kwiatkowsky
Version:1.0.0
"""

2024-12-03 17:18 UTC, MikeSki61 commented on mkl_launch.py
>          if command == "add":
Added comments for the input functions

2024-12-03 17:20 UTC, MikeSki61 commented on mkl_launch.py
> +        if command == "remove":
Removed

2024-12-03 17:21 UTC, MikeSki61 commented on mkl_launch.py
>          name = input("item name: ")
Added more info for the user explaining what the function will do.

2024-12-03 19:22 UTC, SkylerFines requested changes
Added a bit more feedback. Great work so far.

2024-12-03 19:22 UTC, SkylerFines commented on mkl_core.py
> +grocery_list: list[dict[str, float | int | bool | str]] = [
The first comment is just fine. The other two are implied based on the functionality of the type hint. You can leave it if it provides more clarification for you. This one can be resolved.

2024-12-03 19:22 UTC, SkylerFines commented on mkl_core.py
> +grocery_list: list[dict[str, float | int | bool | str]] = [
Looks great, you don't have to write what you added in the comment since I can already see it, just saves you some time and extra work. Make sure the version lines up with the current version in the CHANGELOG. This one can be resolved.

2024-12-03 19:22 UTC, SkylerFines commented on mkl_core.py
> +def add_item(name: str, store: str, cost: float,
So you want doc strings to be under the function. You can also check out getting the docstring generator extension to make this a bit easier. They should include a summary, arguments and return types.  I would suggest revisiting this one.

2024-12-03 19:22 UTC, SkylerFines commented on mkl_core.py
> +    if buy_list:
Looks good, you can resolve this.

2024-12-03 19:22 UTC, SkylerFines commented on mkl_core.py
> +By showing the name of the item as a string, then rounding the cost to
I'm assuming this is meant to be a docstring. refer to above the other comment about docstrings. In addition, Even a summary like this is a bit too verbose. I would suggest a much more brief summary and add a small comment for each step throughout the function instead. TAX should be a constant defined at the top of the module below the imports.

Something like this:

```
# Define a global constant for the default tax rate
TAX = 0.8

def calculate_total_cost(grocery_list: list[dict], round_cost=False, tax=TAX):
    """
    Calculate the total cost of items in a grocery list.

    Parameters:
    grocery_list (list[dict]): A list of dictionaries where each dictionary represents
                               an item with keys 'amount' (int) and 'cost' (float).
    round_cost (bool): If True, rounds the total cost to the nearest integer. Default is False.
    tax (float): The tax rate to apply to the total cost. Default is the global TAX constant.

    Returns:
    float: The total cost after applying tax and optional rounding.
    """
    # Initialize total cost to 0
    total_cost = 0

    # Iterate through each item in the grocery list to calculate total cost
    for item in grocery_list:
        # Calculate the cost for the current item (amount * cost per unit)
        cost = item["amount"] * item["cost"]
        # Add the item's cost to the total cost
        total_cost += cost

    # If rounding is enabled, round the total cost to the nearest integer
    if round_cost:
        total_cost = round(total_cost)

    # If a tax rate is specified, calculate and add tax to the total cost
    if tax:
        tax_cost = total_cost * tax
        total_cost += tax_cost

    # Return the final total cost
    return total_cost
```

2024-12-03 19:22 UTC, SkylerFines commented on mkl_launch.py
Looks, good just ensure the version is accurate. This can be resolved.

2024-12-03 19:22 UTC, SkylerFines commented on mkl_launch.py
> +            mkl_core.add_item(
I would also suggest adding a print statement to tell the user what to do. Make sure for each user input the user understands what they need to input with an example. Also for each function they run there should be a running and completion statement (ie. "Adding an item to the list", "Apple was added to the list")

2024-12-03 19:22 UTC, SkylerFines commented on mkl_launch.py
>          name = input("item name: ")
What I meant by this was to add a print statement so the user will get more information. To address this I would suggest testing you app and put yourself in the place of the user. Ask yourself is it clear what I am supposed to do? If not add a print statement to give them more information. This comment is to the design of your app so you can resolve it when you think it is suffice.

2024-12-03 23:11 UTC, MikeSki61 commented on mkl_core.py
> +By showing the name of the item as a string, then rounding the cost to
I hopefully resolved this. I put the TAX constant as a global variable

2024-12-03 23:11 UTC, MikeSki61 commented on mkl_launch.py
> +            mkl_core.add_item(
Im not sure how to have a print statement showing that the actiin was done.

2024-12-03 23:32 UTC, MikeSki61 commented on mkl_core.py
> +def add_item(name: str, store: str, cost: float,
Revisited and placed doc strings in correct places

2024-12-03 23:32 UTC, MikeSki61 commented on mkl_core.py
> +def calculate_total_cost(grocery_list: str, round_cost=False, tax=0.8):
Made tax a constant, there are errors now

2024-12-03 23:33 UTC, MikeSki61 commented on mkl_launch.py
>          if command == "add":
Added comments

2024-12-04 21:43 UTC, SkylerFines commented on mkl_launch.py
> +            mkl_core.add_item(
You would put the print statement directly after the function is called to le them know what was done. For example after mkl_core.add_item() you can add the print statement. Other wise the changes are all good. great work on this PR!

2024-12-04 21:44 UTC, SkylerFines approved these changes

2024-12-04 22:55 UTC, MikeSki61 commented on mkl_launch.py
> +            mkl_core.add_item(
Placed print statements after the add, remove and edit functions

2024-12-04 22:56 UTC, merged